# FROM openjdk:21-jdk
#
# LABEL name="Cambio-Service"
# LABEL description="API - Cambio service microservice"
# LABEL maintainer="frank-destro@outlook.com"
#
# ADD ./target/5-cambio-service-0.0.1-SNAPSHOT.jar app.jar
#
# ENTRYPOINT ["java","-jar","/app.jar"]
#
# EXPOSE 8000

FROM openjdk:21-jdk
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]


