FROM openjdk:21-jdk

LABEL name="Cambio-Service"
LABEL description="API - Cambio service microservice"
LABEL maintainer="frank-destro@outlook.com"

ADD ./target/5-cambio-service-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]

EXPOSE 8000


