# FROM openjdk:21-jdk
#
# LABEL name="Book-Service"
# LABEL description="API - Book service microservice"
# LABEL maintainer="frank-destro@outlook.com"
#
# ADD ./target/book-service-0.0.1-SNAPSHOT.jar book.jar
#
# ENTRYPOINT ["java","-jar","/book.jar"]
#
# EXPOSE 8200

FROM openjdk:21-jdk
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]