FROM openjdk:21-jdk

LABEL name="Book-Service"
LABEL description="API - Book service microservice"
LABEL maintainer="frank-destro@outlook.com"

ADD ./target/book-service-0.0.1-SNAPSHOT.jar book.jar

ENTRYPOINT ["java","-jar","/book.jar"]

EXPOSE 8200


