server:
    port: 8888
spring:
    application:
        name: erudio-config-server
    output:
        ansi:
            enabled: ALWAYS
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/FrankDestro/dev-config-server
                    #username: username
                    #password: password
                    default-label: main
                    search-paths:
                        - 'greeting-service*'