name: Build and push Docker image
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

       # Set up Docker Buildx (includes Docker Compose)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # login Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          
      # Build Microservice Eureka Server
      - name: Build Eureka Naming Server Container Image
        working-directory: ./naming-server
        run : mvn spring-boot:build-image -DskipTests
      
      # Build Microservice Api Gateway Server
      - name: Build Microservice Api Gateway Server Container Image
        working-directory: ./api-gateway
        run : mvn spring-boot:build-image -DskipTests

       # Build Microservice Cambio Service Jar
      - name: Build Microservice Cambio Service Jar
        working-directory: ./cambio-service
        run : mvn clean package -DskipTests

       # Build Microservice Book Service Jar
      - name: Build Microservice Book Service Jar
        working-directory: ./book-service
        run : mvn clean package -DskipTests

       # Docker Compose Build 
      - name: Docker Compose Build 
        working-directory: ./docker
        run : docker compose build

  
          
        
